spring:
  datasource:
    url: jdbc:postgresql://cyse7374-do-user-15791858-0.m.db.ondigitalocean.com:25060/tasksphere?sslmode=require
    username: doadmin
    password: AVNS_mBzxzKrRdJ8OdbseJF8
    dbcp2:
      test-while-idle: true
      validation-query: select 1
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  mail:
    host: smtp.mailgun.org
    port: 587
    username: postmaster@sandbox8f8b21174b35486ea2dcb63ce40b26b7.mailgun.org
    password: c1a8ad192805bf32c44b9e22cca8cf9c-309b0ef4-64d342d3
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
