spring:
  datasource:
    url: jdbc:postgresql://<dbhost>:<dbport>/tasksphere?sslmode=require
    username: <username>
    password: <password>
    dbcp2:
      test-while-idle: true
      validation-query: select 1
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

mailgun:
  api-key: <api-key>
  domain: <domain>
application:
  security:
    jwt:
      secret-key: <secret-key>
      expiration: 86400000 # a day

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
